Add files.gpg and some bootstrap idemptotency
Weird issue where ms-vscode.Go is transitioning to golang.Go and `code` does
not handle it well. Manually installed for now.

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -2,9 +2,11 @@
 
 set -o errexit
 set -o nounset
+set -o pipefail
 
 # Global vars used in multiple functions
 OS_NAME=$(uname -s)
+VSCODE_EXTENSIONS=~/.config/vscode/extensions.txt
 
 function confirm() {
     read -r -n 1 -p "$1 [Y/n]: "
@@ -26,12 +28,56 @@ function confirm() {
     exit 1
 }
 
+function check_vscode_exts() {
+    # TODO: this should use `--show-versions`
+    diff "$VSCODE_EXTENSIONS" \
+        <(code --list-extensions) \
+        --unchanged-line-format=""  \
+        "$@"
+}
+
+function install_vscode_exts() {
+    xargs printf -- "--install-extension %s " <"$VSCODE_EXTENSIONS" | xargs code
+    echo
+
+    # TODO: some kind of vscode extension "prune" command. Or just uninstall all every time?
+    if ! check_vscode_exts &>/dev/null; then
+        # This check may not be needed since `code` errors if it can't install
+        local UNINSTALLED
+        UNINSTALLED=$(check_vscode_exts \
+            --old-line-format="    %L" \
+            --new-line-format="" \
+            || :
+        )
+
+        if [[ -n $UNINSTALLED ]]; then
+            echo "ERROR: some VSCode extensions were not installed:"
+            echo "$UNINSTALLED"
+            echo
+            return 1
+        fi
+
+        local INSTALLED
+        INSTALLED=$(check_vscode_exts \
+            --old-line-format="" \
+            --new-line-format="    %L" \
+            || :
+        )
+        if [[ -n $INSTALLED ]]; then
+            echo "WARNING: some installed VSCode extensions were not found in $VSCODE_EXTENSIONS:"
+            echo "$INSTALLED"
+            echo
+        fi
+    fi
+}
+
 function setup_macos() {
     # Install homebrew and use it to install basic packages/apps
-    if ! command -v brew >/dev/null && \
+    if ! command -v brew &>/dev/null && \
         confirm "'brew' command not found. Install it? "
     then
         bash -c '$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)'
+        echo
     fi
 
     # TODO: should there be a step to `brew bundle cleanup` here?
@@ -39,23 +85,14 @@ function setup_macos() {
         confirm "Install packages from Brewfile? "
     then
         brew bundle --global install
+        echo
     fi
 
-    # TODO: pre-commit which dumps with `code --list-extensions --show-versions`
-    if ! diff ~/.config/vscode/extensions.txt <(code --list-extensions) &>/dev/null && \
+    # TODO: pre-commit which dumps extensions
+    if ! check_vscode_exts &>/dev/null && \
         confirm "Install VSCode extensions?"
     then
-        xargs printf -- "--install-extension %s " <~/.config/vscode/extensions.txt | xargs code
-    fi
-
-    # TODO: some kind of vscode extension "prune" command. Or just uninstall all every time?
-    if ! diff ~/.config/vscode/extensions.txt <(code --list-extensions) &>/dev/null; then
-        echo
-        echo "WARNING: the following extensions are installed, but not present in extensions.txt:"
-        diff --changed-group-format="    %>" --unchanged-group-format="" \
-            ~/.config/vscode/extensions.txt \
-            <(code --list-extensions)
-        echo
+        install_vscode_exts
     fi
 
     echo "macOS setup is complete!"
@@ -69,6 +106,10 @@ function setup_linux() {
 
 function main() {
     yadm submodule update --init
+
+    GPG_TTY=$(tty)
+    export GPG_TTY
+    yadm decrypt
 
     if [[ "$OS_NAME" == "Darwin" ]]; then
         setup_macos
