Update hooks, encrypted files, and vscode exts
Use full version in vscode extension file (like a lockfile).
Remove symlinks from files.gpg and ignore them in the `encrypt` list.
Ensure yadm hooks are idempotent and share code between hooks + bootstrap.
Add trailing commads to VSCode settings for easier copy-pasting (JSONC).

diff --git a/.config/yadm/hooks/pre_commit b/.config/yadm/hooks/pre_commit
--- a/.config/yadm/hooks/pre_commit
+++ b/.config/yadm/hooks/pre_commit
@@ -3,6 +3,31 @@
 set -o errexit
 set -o nounset
 
-YADM_DIR=~/.config/yadm
+# Start from the base yadm directory
+cd "$(dirname "$YADM_HOOK_REPO")"
 
-shellcheck $YADM_DIR/bootstrap $YADM_DIR/hooks/*
+if [[ "$YADM_HOOK_FULL_COMMAND" =~ (^| )(--no-verify|-n)($| ) ]]; then
+    # Same as `git commit --no-verify`
+    exit 0
+fi
+
+# shellcheck source=utils.sh
+source utils.sh
+
+SHELLCHECK_SOURCES=(
+    bootstrap
+    utils.sh
+    hooks/*
+)
+
+if ! shellcheck "${SHELLCHECK_SOURCES[@]}"; then
+    echo "Some files failed the shellcheck linter!"
+    exit 1
+fi
+
+if ! check_vscode_exts &>/dev/null; then
+    list_vscode_exts >$VSCODE_EXTENSIONS
+    echo "$VSCODE_EXTENSIONS was out-of-date."
+    echo "It has been auto-updated, and should be committed."
+    exit 1
+fi
